# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Thomas Coudrat
tagline:          'Thomas Coudrat'
description:      'PhD candidate. structural & computational biology | computer-aided drug discovery'
url:              http://thomas-coudrat.github.io
baseurl:          /

author:
  name:           'Thomas Coudrat'
  url:            https://twitter.com/TomSilico

paginate:         5

# Custom vars
version:          2.1.0

github:
    repo:         https://github.com/thomas-coudrat/thomas-coudrat.github.io
